### ISSUE TITLE
Dota2 must be in your Steam folder

### ISSUE THREAD

**Issue by robbyz512** [robbyz512/dota2-minify#1]
Hello all Minify detects where your Steam is installed then looks for dota2 in that folder. So if you installed dota2 outside your steam folder then Minify will not work.

This will be fixed soon.

**Comment by Th3Hitman** [comment]
Yup this is exactly the issue I have right now. Thankfully I found this here or else Im just gonna have to wondering around finding a way to point it to the proper folder. Looking forward for the fix soon.

**Comment by Th3Hitman** [comment]
Yup this is exactly the issue I have right now. Thankfully I found this here or else I would've been wondering around try to find a way to point it to the proper folder. Looking forward for the fix soon.

**Comment by robbyz512** [comment]
> Yup this is exactly the issue I have right now. Thankfully I found this here or else I would've been wondering around try to find a way to point it to the proper folder. Looking forward for the fix soon.

I uploaded a version with custom directories fixed on #tech-support channel in my discord server.

Cause I wont be adding it to github for a few days since im working on more features for next release.

**Comment by robbyz512** [comment]
Fixed in latest version.
