### ISSUE TITLE
default menu background is not work 

### ISSUE THREAD

**Issue by BLACKGAMER1221** [robbyz512/dota2-minify#10]
hi, the default menu background is not work and don't remove the main menu background (sky and venge)
pls remove sky, venge and the sand effect from act 2

**Comment by robbyz512** [comment]
unzip this file into Steam\steamapps\common\dota 2 beta\game\dota_minify

[pak04_dir.zip](https://github.com/robbyz512/dota2-minify/files/15479756/pak04_dir.zip)
