### ISSUE TITLE
fix dota2 issue if possible

### ISSUE THREAD

**Issue by BLACKGAMER1221** [robbyz512/dota2-minify#13]
hi
pls check if you can fix this issue: https://github.com/ValveSoftware/Dota2-Gameplay/issues/17942

valve trying to fix gameplay bugs and really don't  care about this one and now we can't play for more than 3 weeks

i know it is because my low end pc but maybe you can do some optimization on match loading 

(it happen after act2 and patch 7.36)

**Comment by robbyz512** [comment]
im not a valve employee, i dont have access to their servers to fix such a problem. 🤦🏻‍♂️ sorry to hear you can't play I'm gonna close this cause it's not related to Minify.
