### ISSUE TITLE
Feature Request: Disable Tipping

### ISSUE THREAD

**Issue by juancpan** [robbyz512/dota2-minify#14]
Hi,

I would like to suggest a new feature to Minify.

Is it possible to disable the tipping(UI element, animation, sounds...)?

Cheers

**Comment by robbyz512** [comment]
I have attempted to remove it multiple times without success. The problem is that tipping was part of DotaPlus when it was released and everything related to DotaPlus is not possible to modify through mods. (since players could get paid features for free then)
