### ISSUE TITLE
a small update earlier broke the minify patch

### ISSUE THREAD

**Issue by waccii** [robbyz512/dota2-minify#16]
![zz](https://github.com/robbyz512/dota2-minify/assets/71301499/25794758-8d28-40c5-b477-b7aed9148d04)

I uninstalled the mods for now to play the game

**Comment by robbyz512** [comment]
Delete this folder and repatch

mods/Default Menu Background/files/panorama/layout/battle_pass/

**Comment by waccii** [comment]
^Thank you, it's working fine now
