### ISSUE TITLE
Dota 2 crashes mid match, during tense moments

### ISSUE THREAD

**Issue by irise4204** [robbyz512/dota2-minify#17]
Hi there, your minify project has really breathed life into my old PCs for Dota 2, much thanks and respect for your project. Since few days dota 2 is crashing mid fights or during initiation when i am using some parts of the minify Mod. I have 3 crash dump files which point at some data that might be associated with your mod. I have appended the important parts of the dmp below. I have also provided the complete crash dmp files if you need them.
[crash_dota2.exe_20240728044510_1.dmp](https://github.com/user-attachments/files/16404328/crash_dota2.exe_20240728044510_1.dmp)
[crash_dota2.exe_20240728183528_1.dmp](https://github.com/user-attachments/files/16404329/crash_dota2.exe_20240728183528_1.dmp)
[crash_dota2.exe_20240728200131_1.dmp](https://github.com/user-attachments/files/16404330/crash_dota2.exe_20240728200131_1.dmp)

My settings fo the Mod are: Auto Accept Match, Dark Terrain, Default Menu Background(I deleted the folder that was causing problems on the other issue), Dotabuff in Profiles, Minify Base Attacks, Minify Spells and Items, Misc Optimization, Mute Ambient Sounds, Remove Foilage, Remove Sprays, Remove Weather Effects
**Crash Dump 1:**
  Console History (reversed)
    4403(5104.035521):  opvar_get_float operator import_random_entry_start::get_no_repeat_opvar in dota_battleend failed to get field dota_change_this_opvar_name
    4402(5071.761560):  2240:item_flask::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell -5 is outside of cell bounds (0->128) @(-17865.015625 -11400.239258 -353.460968)
    4401(5061.253070):  2266:item_tango::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 167 is outside of cell bounds (0->128) @(26370.937500 210.811035 0.000000)
    4400(5055.286512):  2240:item_flask::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 155 is outside of cell bounds (0->128) @(23445.410156 10228.544922 0.000008)
    4399(5055.286498):  2234:item_boots::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 147 is outside of cell bounds (0->128) @(21290.875000 11459.957031 0.000008)
    4398(5055.286477):  2233:item_tango::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 146 is outside of cell bounds (0->128) @(21161.519531 11505.648438 0.000008)
    4397(5033.623205):  242:item_recipe_ring_of_basilius::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 138 is outside of cell bounds (0->128) @(19104.384766 10303.091797 0.000000)
    4396(5022.618962):  1807:item_slippers::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell -6 is outside of cell bounds (0->128) @(-17928.457031 10487.691406 -353.460968)
    4395(5009.257485):  1922:item_ward_sentry::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 139 is outside of cell bounds (0->128) @(19432.855469 -8987.625977 0.000000)
    4394(5009.257473):  1901:item_enchanted_mango::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 134 is outside of cell bounds (0->128) @(17982.419922 -8182.043457 0.000000)
    4393(5009.257460):  1884:item_ring_of_regen::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 134 is outside of cell bounds (0->128) @(17982.419922 -8182.043457 0.000000)
    4392(5009.257440):  1880:item_wind_lace::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 134 is outside of cell bounds (0->128) @(17982.419922 -8182.043457 0.000000)
    4391(4988.286388):  1807:item_slippers::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 173 is outside of cell bounds (0->128) @(28047.201172 5390.072266 0.000008)
    4390(4966.621462):  1316:item_recipe_magic_wand::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 130 is outside of cell bounds (0->128) @(16911.386719 -4813.350586 -135.624985)
    4389(4961.085990):  994:item_recipe_bracer::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 129 is outside of cell bounds (0->128) @(16821.123047 -1290.191406 0.000000)
    4388(4961.085958):  993:item_gauntlets::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 129 is outside of cell bounds (0->128) @(16821.123047 -1290.191406 0.000000)
    4387(4943.927476):  opvar_get_float operator import_random_entry_start::get_no_repeat_opvar in dota_battleend failed to get field dota_change_this_opvar_name
    4386(4936.489045):  CDOTA_Hud_Main::DeleteGameEndScreen deleted GameEndContainer

**Crash Dump 2:**
  Console History (reversed)
    1797(2293.883869):  1690:item_branches::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellY cell -2 is outside of cell bounds (0->128) @(-1400.080566 -16959.089844 -541.333374)
    1796(2284.039525):  1690:item_branches::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell -22 is outside of cell bounds (0->128) @(-22172.535156 -303.371094 0.000008)
    1795(2273.948534):  1356:item_magic_stick::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 133 is outside of cell bounds (0->128) @(17763.566406 -9522.685547 -712.000000)
    1794(2273.948518):  206:item_branches::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 133 is outside of cell bounds (0->128) @(17763.566406 -9522.685547 -712.000000)
    1793(2264.314564):  1566:item_magic_stick::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 158 is outside of cell bounds (0->128) @(24083.382812 391.972168 0.000000)
    1792(2264.314543):  1565:item_branches::m_vecOrigin CNetworkOriginCellCoordQuantizedVector m_cellX cell 158 is outside of cell bounds (0->128) @(24083.382812 391.972168 0.000000)
    1791(2232.899930):  CDOTA_Hud_Main::DeleteGameEndScreen deleted GameEndContainer

**Comment by khanshaib11** [comment]
bump

**Comment by robbyz512** [comment]
Taking a break from this project for a while, I recommend you join discord and ask for help there maybe some other people can help you out.
