### ISSUE TITLE
Dota Pre match Statistics 

### ISSUE THREAD

**Issue by khanshaib11** [robbyz512/dota2-minify#18]
Hey Dev! thanks for this amazing sweet mod which helps hundreds of players in dota 2 to play the game . I am currently running the mod and it is amazing , so now i want to know or if u can add the pre match statistic like overwolf or any other thing . where we can see 9 players statistic of 10 or 5 games ? also can u enhence the networth system  and finally when will be new update availible

**Comment by robbyz512** [comment]
working on unrelated projects right now but I'll update minify if it stops working, right now its still fine.
