### ISSUE TITLE
Unable to boot Dota 2 due to a Battle Pass Reward issue.

### ISSUE THREAD

**Issue by carmelopaz0708** [robbyz512/dota2-minify#2]
When booting up Dota 2, I would get the error message below.

![Screenshot 2022-09-17 084631](https://user-images.githubusercontent.com/45812970/190833960-a92dbc9b-2e22-4e85-8e9c-07b182cd24ee.png)

It doesn't always happen, but when it does, it locks me out of the loading screen. After that, the game would validate on its own. Even after the files have been validated (and after running Minify and Dota2Patcher), it would throw this error.

How to Recreate:
1. Open Minify and patch game.
2. Open Dota2Patcher and Patch Gameinfo (option 4)
3. Open Dota 2 from Steam.

**Comment by robbyz512** [comment]
This is not related to Minify since this error is caused by an invalid items_game.txt file which Minify doesn't use. 

It's most likely [NoBling](https://github.com/No-Bling/DOTA) mod. So just update that mod to fix it or whichever else other mods you use. 👍
