### ISSUE TITLE
Problem finding DOTA 2 files.

### ISSUE THREAD

**Issue by motkacul** [robbyz512/dota2-minify#20]
Hello, I have a problem finding DOTA 2 game files, when I launch the application it says that it did not find the game files, and when I try to find them myself they are not there even after reinstalling the application, but when I open the explorer on the computer everything is there . I hope there is a solution.

**Comment by robbyz512** [comment]
join discord

**Comment by motkacul** [comment]
> join discord

link pls

**Comment by robbyz512** [comment]
https://discord.gg/2YDnqpbcKM

**Comment by motkacul** [comment]
> https://discord.gg/2YDnqpbcKM

thx)))
