### ISSUE TITLE
Documents folder needs to be in C: drive

### ISSUE THREAD

**Issue by robbyz512** [robbyz512/dota2-minify#4]
Make sure you have your Documents folder in C: drive if Minify doesn't start.
https://www.cedarville.edu/insights/computer-help/post/how-to-set-default-document-folder-location-in-windows

You can also just create this file in this path yourself.

C:\\Users\YOUR_USERNAME\Documents\dota2path_minify.txt

I'll fix this next version.

**Comment by jijiezheng** [comment]
@robbyz512 how can I recompile a file ,for put into the VPK? 
I edited a file in panorama/layout/popups/popup_accept_match.xml,but can't recompile it into popup_accept_match.vxml_c.
can u tell me how to recompile it? I had read [Dota2 Modding Tutorials],but it said "This page is under construction" T_T

**Comment by robbyz512** [comment]
> @robbyz512 how can I recompile a file ,for put into the VPK? I edited a file in panorama/layout/popups/popup_accept_match.xml,but can't recompile it into popup_accept_match.vxml_c. can u tell me how to recompile it? I had read [Dota2 Modding Tutorials],but it said "This page is under construction" T_T

if you join my discord I'll help you there.
