### ISSUE TITLE
Tree mod doesnt work for now.

### ISSUE THREAD

**Issue by Th3Hitman** [robbyz512/dota2-minify#7]
It says "VAC detected modified files". I think this probably Dota2Patcher issue.

**Comment by robbyz512** [comment]
https://github.com/Wolf49406/Dota2Patcher/issues/46#issuecomment-1303626109

I posted a solution here.

**Comment by Th3Hitman** [comment]
Thanks for the fast reply. It doesnt seems to work for me but I may have done something wrong. I will keep trying again.

It works. I dont know why for some reason I have to choose patch all. Patch gameinfo only doesnt seems to work even if I do it 2 times.
