### ISSUE TITLE
Cant use the use minify.exe on my windows 7

### ISSUE THREAD

**Issue by lordamir20132** [robbyz512/dota2-minify#8]
I get this error The instruction at 0xfd551b44 referenced memory at 0x000000000. The memory could not be written

**Comment by robbyz512** [comment]
Windows 10/11 only right now sorry.

**Comment by lordamir20132** [comment]
> Windows 10/11 only right now sorry.

Sad I wish I could have it.
Its ok I will wait until you release a support for windows 7 Good Luck Sir
